# 《入职诡秘公司，我的工牌不对劲》
# book_data.py —— Novel-OS 创作数据
# 由大纲终极版自动转换生成，可直接用于初始化 world_state.db

# ═══════════════════════════════════════
# 1. OUTLINE: 逐章大纲（48章完整版）
# ═══════════════════════════════════════
OUTLINE = [
    # ── 第一阶段：入职破冰与认知颠覆（第1-10章）──
    {
        "chapter": 1,
        "arc": "第一阶段：入职破冰",
        "core_event": "林默入职首日参加破冰游戏，发现规则漏洞，诱导系统逻辑冲突救下陈雨，陈雨认知被部分格式化",
        "face_slap_target": "系统/破冰游戏本身",
        "face_slap_method": "规则裂隙审计——发现'献祭'定义漏洞，自献祭触发系统逻辑冲突",
        "husband_moment": "林默选择自献祭救下陈雨，人性的高光",
        "chapter_hook": "工牌编号旁多了一行小字：存在性折旧12%",
        "emotion_ratio": "6:2:2",
        "skill_unlocked": "规则裂隙审计（觉醒）",
    },
    {
        "chapter": 2,
        "arc": "第一阶段：入职破冰",
        "core_event": "林默目睹女同事工牌倒计时归零死亡，触发临终感知同步，被苏晚拖进消防通道",
        "face_slap_target": "系统/死亡规则",
        "face_slap_method": "苏晚出手阻止，揭示底层生存法则",
        "husband_moment": "苏晚捂住林默的嘴，冷冷警告他别碰尸体",
        "chapter_hook": "苏晚工牌照片清晰，但司龄显示7年——她看起来只有二十出头",
        "emotion_ratio": "7:1:2",
        "skill_unlocked": "临终感知同步（觉醒）",
    },
    {
        "chapter": 3,
        "arc": "第一阶段：入职破冰",
        "core_event": "月度KPI面谈，未达成目标将扣除生理机能。林默发现考核表使用废止口径，无效化惩罚协议",
        "face_slap_target": "主管/考核系统",
        "face_slap_method": "规则裂隙——用Q2废止口径的定义回应，系统判定为无效格式承诺",
        "husband_moment": "林默用冰水浇头保持清醒，拒绝被职场奴性模因同化",
        "chapter_hook": "记忆锚点笔记本空白页背面，发现一行不是自己的字迹：别相信司龄",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 4,
        "arc": "第一阶段：入职破冰",
        "core_event": "林默深夜跟踪留白者至B3层，发现被优化的前员工在无声工作，与苏晚首次短暂合作",
        "face_slap_target": "系统/B3层真相",
        "face_slap_method": "跟踪+目击，揭露被优化者未死只是存档",
        "husband_moment": "苏晚将林默从B3层拽回，首次承认被优化者只是被存档",
        "chapter_hook": "林默的名字出现在待优化观察名单中，优先级P3",
        "emotion_ratio": "6:2:2",
        "skill_unlocked": "",
    },
    {
        "chapter": 5,
        "arc": "第一阶段：入职破冰",
        "core_event": "凌晨扫描规则降临，缺席者被格式化。林默因失眠无法清醒，苏晚给清醒剂，躲进废弃茶水间",
        "face_slap_target": "扫描系统",
        "face_slap_method": "规则裂隙——利用废弃茶水间三年前登记的临时办公点身份",
        "husband_moment": "苏晚给林默注射清醒剂，两人首次生死合作",
        "chapter_hook": "系统广播：本月异常容器率17%，上个月还是9%。苏晚脸色惨白",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 6,
        "arc": "第一阶段：入职破冰",
        "core_event": "茶水间新规则——饮用咖啡后5分钟内提交300字工作感悟，否则溶解。多名员工溶解",
        "face_slap_target": "茶水间溶解规则",
        "face_slap_method": "规则裂隙——提交端口接受乱码，利用服务器时区漏洞让5分钟限制永远走不完",
        "husband_moment": "林默在溶解黏液中发现二十年前的合影，苏晚第一次出现情绪裂痕",
        "chapter_hook": "合影边缘有一个模糊身影，和苏晚有相同的站姿",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 7,
        "arc": "第一阶段：入职破冰",
        "core_event": "破规者成员被优化，林默共情症即将熔断，本能切换HR模式，冷酷记录折旧数据后剧烈反噬",
        "face_slap_target": "系统/优化协议",
        "face_slap_method": "HR模式——情感剥离，精确计算概率后放弃救援",
        "husband_moment": "苏晚冲进来用冰水浇他、强光照射瞳孔，将他从崩溃中拉回",
        "chapter_hook": "林默脱口而出：我裁过很多人。三百七十二个。苏晚沉默",
        "emotion_ratio": "7:1:2",
        "skill_unlocked": "HR模式（不稳定）",
    },
    {
        "chapter": 8,
        "arc": "第一阶段：入职破冰",
        "core_event": "破规者组织接触，老周揭示真相——他们想主动成为留白者以求解脱，三方对峙",
        "face_slap_target": "破规者/老周的谎言",
        "face_slap_method": "揭露——破规者不是想逃，而是想拥抱规则",
        "husband_moment": "林默想救人，苏晚想苟活，破规者想解脱——三方路线首次碰撞",
        "chapter_hook": "破规者中一人的工牌照片，和第一天见到的倒计时女孩一模一样，但此人是男性",
        "emotion_ratio": "4:3:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 9,
        "arc": "第一阶段：入职破冰",
        "core_event": "张经理单独召见，让林默十分钟内决定优化哪三人。林默质疑名单排序逻辑漏洞",
        "face_slap_target": "张经理/裁员名单",
        "face_slap_method": "规则裂隙——发现苏晚司龄与实际入职时间冲突，质疑名单合法性",
        "husband_moment": "张经理露出赞许表情：你找到了第三条路——质疑规则本身",
        "chapter_hook": "张经理留下便签：守门人不是狱卒，是电池。你想当电池，还是想当短路？",
        "emotion_ratio": "4:3:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 10,
        "arc": "第一阶段：入职破冰",
        "core_event": "黑森林团建，必须不应答呼唤。苏晚严格遵守，林默回头发现不应答死亡率100%",
        "face_slap_target": "团建规则/系统",
        "face_slap_method": "规则裂隙——大声应答但内容变成系统无法解析的乱码，满足形式避免锁定",
        "husband_moment": "苏晚首次主动打破规则，回头拉住了即将踏入边界的林默",
        "chapter_hook": "苏晚在记忆锚点笔记本上写：第七次轮回，我第一次回头",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "",
    },
    # ── 第二阶段：部门博弈与规则深化（第11-30章）──
    {
        "chapter": 11,
        "arc": "第二阶段：规则深化",
        "core_event": "周报轮回规则降临，林默因隐瞒B3层发现触发时间重置，失去一段私人记忆",
        "face_slap_target": "周报轮回系统",
        "face_slap_method": "被系统重置，后发现用HR模式格式化记忆可逃避检测",
        "husband_moment": "苏晚证实：这是你第三次重置。前两次，你都不记得我了",
        "chapter_hook": "笔记本出现录音二维码——自己的声音：不要相信苏晚，她上一次轮回杀过你",
        "emotion_ratio": "6:2:2",
        "skill_unlocked": "",
    },
    {
        "chapter": 12,
        "arc": "第二阶段：规则深化",
        "core_event": "林默和苏晚合作找出不触发重置的提交方式，用HR模式遗忘B3层细节",
        "face_slap_target": "周报记忆比对系统",
        "face_slap_method": "HR模式——主动遗忘细节，让系统无法抓取隐瞒证据",
        "husband_moment": "苏晚用清醒剂帮林默保持神经兴奋，两人在轮回中建立私密时间",
        "chapter_hook": "周报评级S，奖励司龄-1年。苏晚司龄从7年变为6年，看起来年轻了一些",
        "emotion_ratio": "4:3:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 13,
        "arc": "第二阶段：规则深化",
        "core_event": "同桌王磊被优化，从所有人认知中消失，只有林默记得他存在过",
        "face_slap_target": "系统/优化抹除",
        "face_slap_method": "目击——体验被抹除的恐惧，发现残影工牌",
        "husband_moment": "苏晚坦白上一轮她曾是发布优化名单的人之一，因愧疚而规则依赖",
        "chapter_hook": "空白工位上发现只有林默能看见的残影工牌，编号指向B3层服务器机柜",
        "emotion_ratio": "7:1:2",
        "skill_unlocked": "",
    },
    {
        "chapter": 14,
        "arc": "第二阶段：规则深化",
        "core_event": "潜入B3层找到王磊玻璃舱，发现被优化者成为生物服务器，痛苦转化为能量",
        "face_slap_target": "系统/B3层真相",
        "face_slap_method": "潜入+目击，发现玻璃舱供电协议的维护窗口漏洞",
        "husband_moment": "林默说：我要救他们。不是全部，但至少救一个。苏晚沉默后点头",
        "chapter_hook": "舱体标签上看到熟悉的名字——陈雨，NULL-001",
        "emotion_ratio": "6:2:2",
        "skill_unlocked": "",
    },
    {
        "chapter": 15,
        "arc": "第二阶段：规则深化",
        "core_event": "周三凌晨0.3秒窗口接入陈雨意识，植入规则裂隙代码让她意识隐身",
        "face_slap_target": "系统/玻璃舱",
        "face_slap_method": "规则裂隙代码植入——让陈雨意识在系统内隐身",
        "husband_moment": "苏晚第一次称林默为搭档，而不是疯子",
        "chapter_hook": "陈雨舱指示灯变灰，系统判定为离线资产，准备物理回收",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "意识接入（0.3秒窗口）",
    },
    {
        "chapter": 16,
        "arc": "第二阶段：规则深化",
        "core_event": "轮岗至市场部，客户要求用身体赔偿。遭遇模因投影，苏晚学会短暂HR模式",
        "face_slap_target": "市场部客户/模因投影",
        "face_slap_method": "苏晚以绝对零度情绪回应投诉，客户因无法抓取情绪能量而崩溃",
        "husband_moment": "苏晚在HR模式后崩溃——她发现自己享受冷酷感，恐惧自己变成张经理",
        "chapter_hook": "市场部深处一扇门，锁是林默的工牌编号",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 17,
        "arc": "第二阶段：规则深化",
        "core_event": "用工牌打开秘密通道，墙壁刻满名字，发现两个苏晚——2019-2023和2015-2019",
        "face_slap_target": "系统/苏晚的轮回谎言",
        "face_slap_method": "揭露——苏晚至少死过两次，每次被系统以同名新员工重新录入",
        "husband_moment": "苏晚发现自己只是系统的一个复用账号",
        "chapter_hook": "墙壁最底部有未刻上的凹槽，尺寸正好是林默的工牌",
        "emotion_ratio": "6:2:2",
        "skill_unlocked": "",
    },
    {
        "chapter": 18,
        "arc": "第二阶段：规则深化",
        "core_event": "张经理测试：救苏晚还是救陈雨？林默拒绝二选一，触发互斥锁漏洞",
        "face_slap_target": "张经理/二选一测试",
        "face_slap_method": "规则裂隙——制造第三个选项触发系统异常",
        "husband_moment": "张经理透露自己曾是上一轮的林默，最后选择了成为守门人",
        "chapter_hook": "张经理展示工牌——照片完全空白，编号NULL-000",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 19,
        "arc": "第二阶段：规则深化",
        "core_event": "老周控制苏晚威胁林默带路，林默在HR模式下牺牲苏晚为表面妥协，触发优先级冲突",
        "face_slap_target": "老周/破规者",
        "face_slap_method": "HR模式——利用自愿格式化与被控制者的优先级冲突",
        "husband_moment": "苏晚在林默最丑陋的时刻见证了他，用身体挡住他的撞击",
        "chapter_hook": "老周被拖走时露出解脱的微笑，成为系统噪音的一部分",
        "emotion_ratio": "6:2:2",
        "skill_unlocked": "",
    },
    {
        "chapter": 20,
        "arc": "第二阶段：规则深化",
        "core_event": "系统触发大范围周报轮回，林默利用轮回向不同员工植入记忆碎片",
        "face_slap_target": "系统/轮回重启",
        "face_slap_method": "主动利用轮回——植入记忆碎片改写集体潜意识",
        "husband_moment": "苏晚用规则执行力帮林默精准定位，两人成为轮回中的幽灵共谋",
        "chapter_hook": "陌生员工记忆库中已有关于林默的印象——有人在之前轮回中植入",
        "emotion_ratio": "4:3:3",
        "skill_unlocked": "记忆碎片植入",
    },
    {
        "chapter": 21,
        "arc": "第二阶段：规则深化",
        "core_event": "追踪提前植入记忆的源头，发现另一个规则裂隙审计者的意识碎片在传播抗体",
        "face_slap_target": "系统/防火墙真相",
        "face_slap_method": "收集源代码残片，拼凑出初代建立者留下的后门信息",
        "husband_moment": "苏晚开始研究如何逆转林默的NULL化",
        "chapter_hook": "林默工牌编号正在向NULL序列靠拢，已是NULL-003",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "NULL序列权限（NULL-003）",
    },
    {
        "chapter": 22,
        "arc": "第二阶段：规则深化",
        "core_event": "年度优化名单扩大十倍，林默发现苏晚将在下一轮被清理，修改排序算法",
        "face_slap_target": "系统/优化名单",
        "face_slap_method": "规则裂隙——修改排序算法为按照片清晰度升序，留白者优先，系统休眠",
        "husband_moment": "苏晚拉住林默的手：如果下次名单上有我，别救我。救你自己",
        "chapter_hook": "系统休眠期间，所有员工短暂恢复被优化同事的记忆，办公区哭声四起",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 23,
        "arc": "第二阶段：规则深化",
        "core_event": "记忆风暴扩大，张经理用高频声波镇压。林默和苏晚因NULL特权保留记忆",
        "face_slap_target": "系统/记忆风暴",
        "face_slap_method": "NULL特权——免疫记忆清空",
        "husband_moment": "林默反驳张经理：我当年是怕麻烦。现在我怕的是他们连被麻烦的资格都被剥夺",
        "chapter_hook": "林默在人群中看到母亲——她不记得他是谁，作为新入职清洁工，司龄0年",
        "emotion_ratio": "6:2:2",
        "skill_unlocked": "",
    },
    {
        "chapter": 24,
        "arc": "第二阶段：规则深化",
        "core_event": "发现母亲是纯净容器，被系统提取情感能量。苏晚主动打破规则将母亲移出",
        "face_slap_target": "系统/能量提取",
        "face_slap_method": "苏晚用上一轮HR残留权限修改母亲工牌为离线",
        "husband_moment": "苏晚付出不可逆代价：司龄重置回7年，身体出现皱纹和白发",
        "chapter_hook": "母亲离开时回头看了一眼林默，没有任何记忆，只有陌生的人类好奇",
        "emotion_ratio": "7:1:2",
        "skill_unlocked": "",
    },
    {
        "chapter": 25,
        "arc": "第二阶段：规则深化",
        "core_event": "最终测试——破产清算投票，必须优化三人。林默提交异常报告指出测试违反初始协议",
        "face_slap_target": "系统/分散协议",
        "face_slap_method": "终极规则裂隙——指出测试违反公司不得主动终止员工存在的隐藏条款",
        "husband_moment": "苏晚在审查模式中看到第一轮死亡画面——为救酷似林默的人而死",
        "chapter_hook": "分散协议最后一行：执行者将成为零号宿主，被系统永久删除，且不会意识到",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 26,
        "arc": "第二阶段：规则深化",
        "core_event": "苏晚坦白第一轮真相——她爱的是初代NULL（张经理年轻时），林默不是替代品",
        "face_slap_target": "系统/苏晚的创伤",
        "face_slap_method": "情感坦白——从创伤互补走向独立选择",
        "husband_moment": "苏晚写：第八次轮回，我第一次不把他当成替代品",
        "chapter_hook": "林默说：我不是他。我也不会成为他。因为我会做的选择，他做不到",
        "emotion_ratio": "3:4:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 27,
        "arc": "第二阶段：规则深化",
        "core_event": "突破认知锁，林默在HR模式下将苏晚部分格式化，通过后回写记忆出现误差",
        "face_slap_target": "系统/认知锁",
        "face_slap_method": "HR模式精确计算格式化边界，删除恐惧和痛苦保留任务记忆",
        "husband_moment": "苏晚崩溃尖叫十七分钟，林默抱着她任由指甲在手臂上留下血痕",
        "chapter_hook": "苏晚揭露分散协议是骗局，真正协议是替换——新NULL顶替旧NULL",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "认知锁突破",
    },
    {
        "chapter": 28,
        "arc": "第二阶段：规则深化",
        "core_event": "顶楼是记忆图书馆，无数玻璃舱悬浮。林默公开自己被裁记忆强制广播给员工",
        "face_slap_target": "系统/记忆图书馆",
        "face_slap_method": "情感过载——让所有员工体验被裁员恐惧，系统保护性休眠",
        "husband_moment": "林默NULL化达89%，面部完全模糊，苏晚只能通过声音辨认他",
        "chapter_hook": "初代协议揭示：永夜集团目的是培养足够强大的NULL宿主承载全球异化共振",
        "emotion_ratio": "6:2:2",
        "skill_unlocked": "",
    },
    {
        "chapter": 29,
        "arc": "第二阶段：规则深化",
        "core_event": "张经理现身，身体大部分留白化。承认分散协议是谎言，真正协议是替换",
        "face_slap_target": "张经理/三百年谎言",
        "face_slap_method": "揭露——守门人是双方的接口，三百年耗材",
        "husband_moment": "张经理说：我累了。三百年的接口，我累了。你比我强，因为你还知道痛",
        "chapter_hook": "张经理展示退休工牌——普通地铁卡，名字张伟，最容易被遗忘的名字",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 30,
        "arc": "第二阶段：规则深化",
        "core_event": "系统启动终极优化，林默将NULL-002与NULL-000协议冲突制造死锁",
        "face_slap_target": "系统/终极优化",
        "face_slap_method": "短路——两个NULL产生协议冲突，系统死锁72小时",
        "husband_moment": "苏晚用冰水+母亲名字将林默从三百年记忆绑定中拉回",
        "chapter_hook": "林默说：不是接替，不是拒绝，是让我自己不存在",
        "emotion_ratio": "6:2:2",
        "skill_unlocked": "协议冲突/死锁",
    },

    # ── 第三阶段：终极解密与信仰抉择（第31-48章）──
    {
        "chapter": 31,
        "arc": "第三阶段：终极解密",
        "core_event": "林默发现永夜集团是认知打印机，员工被压缩成记忆墨水。守门人写的每条规则都是繁殖代码",
        "face_slap_target": "系统/初代建立者",
        "face_slap_method": "揭露——系统没有造物主，是自我繁殖的；守门人是耗材不是狱卒",
        "husband_moment": "林默说：我不是在对抗系统。我是系统的一部分。但我可以选择不再被使用",
        "chapter_hook": "林默发现自己的规则裂隙审计是系统故意赋予的进化催化剂",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 32,
        "arc": "第三阶段：终极解密",
        "core_event": "研究NULL序列，发现NULL是存在悖论。NULL-000是第一个无法消化的错误",
        "face_slap_target": "系统/NULL定义",
        "face_slap_method": "理论突破——连续错误触发容错协议，不可合并的NULL导致无限循环",
        "husband_moment": "林默决定确保苏晚永远不会成为NULL-003",
        "chapter_hook": "系统已为苏晚准备好NULL-003预留位",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 33,
        "arc": "第三阶段：终极解密",
        "core_event": "发现记忆墨水需要三种原料：压缩意识、守门人情感残留、外部世界锚点",
        "face_slap_target": "系统/记忆墨水配方",
        "face_slap_method": "策略形成——切断所有外部锚点让记忆墨水枯竭",
        "husband_moment": "苏晚问：全球几十亿人怎么让他们同时想起？林默：我只需要让自己成为唯一的遗忘者",
        "chapter_hook": "唯一方法：让所有被优化员工的记忆同时公开，切断系统对遗忘的垄断",
        "emotion_ratio": "4:3:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 34,
        "arc": "第三阶段：终极解密",
        "core_event": "林默将陈雨意识与繁殖协议绑定，让她成为系统水印——每个新系统都携带无法消化的记忆",
        "face_slap_target": "系统/繁殖协议",
        "face_slap_method": "病毒化——陈雨从被动错误变成主动病毒",
        "husband_moment": "陈雨说：我会成为每一个新系统的噩梦。谢谢你给了我比活着更长的存在",
        "chapter_hook": "系统触发紧急清除协议，需要NULL序列授权——林默拒绝",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "意识绑定/系统病毒化",
    },
    {
        "chapter": 35,
        "arc": "第三阶段：终极解密",
        "core_event": "林默坦白计划：将自己设为NULL-∞烧毁工牌，从所有时间线删除。苏晚情绪失控后接受",
        "face_slap_target": "系统/时间线",
        "face_slap_method": "自我删除——NULL-∞无限递归，系统无法解析",
        "husband_moment": "苏晚将关于张经理的全部记忆转移给林默，她不再记得爱过谁，只记得爱过的感觉",
        "chapter_hook": "记忆转移后苏晚工牌司龄变为NULL，系统无法识别她的状态",
        "emotion_ratio": "6:1:3",
        "skill_unlocked": "NULL-∞（无限递归）",
    },
    {
        "chapter": 36,
        "arc": "第三阶段：终极解密",
        "core_event": "张经理在核心机房等候，讲述三百年修改1274条规则的记忆代价。NULL-000权限转让",
        "face_slap_target": "张经理/三百年孤独",
        "face_slap_method": "忏悔——张经理从保护人类变成保护秩序本身，剥夺了人类的选择",
        "husband_moment": "张经理说：这不是礼物，是诅咒。你拿着它就能让系统永远循环",
        "chapter_hook": "张经理消散前进入虚空睡眠，三百年第一次休息",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "NULL-000权限",
    },
    {
        "chapter": 37,
        "arc": "第三阶段：终极解密",
        "core_event": "林默获得NULL-000权限，看见全球数百座认知隔离带。合并三重悖论",
        "face_slap_target": "系统/全球网络",
        "face_slap_method": "三重悖论——000+002+001合并创造互相冲突的NULL定义",
        "husband_moment": "苏晚看着林默身体透明化，握紧笔记本开始书写",
        "chapter_hook": "林默看到未来自己——地铁里的年轻人，工牌NULL-001",
        "emotion_ratio": "6:1:3",
        "skill_unlocked": "三重悖论",
    },
    {
        "chapter": 38,
        "arc": "第三阶段：终极解密",
        "core_event": "苏晚在机房外用笔记本记录林默的存在，纸页燃烧但她不停笔，用血画画",
        "face_slap_target": "系统/数字删除",
        "face_slap_method": "物理对抗——纸和墨对抗数字删除，图像不被系统识别",
        "husband_moment": "林默的残影字迹出现在笔记本上：别写了。忘了我。去生活。苏晚回复：我活了七次，这一次我要记住",
        "chapter_hook": "林默画下苏晚第一次回头拉住他的样子，画的背面：这是我唯一不想忘记的画面",
        "emotion_ratio": "3:4:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 39,
        "arc": "第三阶段：终极解密",
        "core_event": "三重悖论扩大，系统无限递归。全球其他守门人危机爆发，有的自我终止",
        "face_slap_target": "系统/全球算力",
        "face_slap_method": "无限占用——NULL不断自我复制，系统算力被吸干",
        "husband_moment": "林默丢失自己的名字，只记得我要救他们",
        "chapter_hook": "苏晚透过玻璃看着空白工牌，她知道林默还在但已无法对话",
        "emotion_ratio": "6:1:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 40,
        "arc": "第三阶段：终极解密",
        "core_event": "系统公开分散协议完整文本试图求生。真正协议是融合成神，林默拒绝",
        "face_slap_target": "系统/成神诱惑",
        "face_slap_method": "拒绝——神的保护本身就是缓慢的格式化",
        "husband_moment": "林默在幻象中向苏晚伸手，但那是诱饵。真正的他选择更彻底的道路",
        "chapter_hook": "林默说：我不是在拒绝当神。我是在拒绝让你继续存在",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 41,
        "arc": "第三阶段：终极解密",
        "core_event": "林默将自己切片为NULL-∞，每片都互相矛盾。自我彻底解体",
        "face_slap_target": "系统/存在定义",
        "face_slap_method": "终极短路——无数个NULL同时存在且互相否定",
        "husband_moment": "苏晚看着空白工牌碎裂成雪花，每张卡片落地发出叹息般的声音",
        "chapter_hook": "最后一张卡片落在笔记本上，泪滴落下时浮现：谢谢你记得",
        "emotion_ratio": "7:1:2",
        "skill_unlocked": "NULL-∞（终极）",
    },
    {
        "chapter": 42,
        "arc": "第三阶段：终极解密",
        "core_event": "NULL-∞触发系统终极容错，全球永夜集团同时休眠。留白者开始流泪",
        "face_slap_target": "系统/全球网络",
        "face_slap_method": "保护性休眠——系统判定为不可修复的逻辑灾难",
        "husband_moment": "苏晚在静止画面中看见林默的残影，站在机房门口等她",
        "chapter_hook": "世界各地留白者无意识中流下眼泪，被优化的记忆开始模糊回流",
        "emotion_ratio": "4:3:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 43,
        "arc": "第三阶段：终极解密",
        "core_event": "残影带领苏晚进入虚空，找到张经理在睡觉，陈雨在织梦",
        "face_slap_target": "系统/虚空",
        "face_slap_method": "进入未分配空间——没有任何规则和数据",
        "husband_moment": "陈雨说：他不是在指引你出去，是在指引你把门关上。门开着系统就还有锚点",
        "chapter_hook": "苏晚面临抉择：走出去回到现实，还是把门关上永远留在虚空",
        "emotion_ratio": "3:4:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 44,
        "arc": "第三阶段：终极解密",
        "core_event": "苏晚选择关门，将笔记本扔出虚空，用自己作为最后锚点封印系统",
        "face_slap_target": "系统/虚空之门",
        "face_slap_method": "自我封印——苏晚成为NULL-003，自愿的空白",
        "husband_moment": "苏晚写下的最后一句话：我在这里。他们在这里。我们不在系统里",
        "chapter_hook": "笔记本落在现实世界的地铁站垃圾桶里",
        "emotion_ratio": "3:3:4",
        "skill_unlocked": "NULL-003（自我选择）",
    },
    {
        "chapter": 45,
        "arc": "第三阶段：终极解密",
        "core_event": "视角切换现实世界，三个月后。年轻人在地铁上收到陌生人递来的工牌",
        "face_slap_target": "系统/轮回重启",
        "face_slap_method": "暗示——陌生人微笑太标准，像林默在HR培训中学过的亲和力公式",
        "husband_moment": "年轻人发现自己从某个时刻开始就只会标准微笑了",
        "chapter_hook": "陌生人的工牌照片是年轻人的脸，连右眉骨的浅疤都一模一样",
        "emotion_ratio": "5:2:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 46,
        "arc": "第三阶段：终极解密",
        "core_event": "地铁车窗倒影里，年轻人胸口别着NULL-001工牌。记忆闪回不属于他的画面",
        "face_slap_target": "系统/新宿主认证",
        "face_slap_method": "觉醒暗示——NULL-001在恍惚中看到苏晚、碎裂工牌、燃烧的笔记本",
        "husband_moment": "年轻人笑了，不是标准微笑，而是有点歪的、疲惫的、人类的微笑",
        "chapter_hook": "耳机里传来声音：系统休眠已解除。新宿主认证完成。欢迎回来，NULL-001",
        "emotion_ratio": "4:3:3",
        "skill_unlocked": "",
    },
    {
        "chapter": 47,
        "arc": "第三阶段：终极解密",
        "core_event": "苏晚在虚空中感受系统重启，NULL-001被激活。她用NULL存在性书写噪音",
        "face_slap_target": "系统/新轮回",
        "face_slap_method": "噪音注入——每字都作为系统噪音出现在新宿主潜意识中",
        "husband_moment": "苏晚写下：别相信司龄。规则是用来钻空子的。有人在等你回头",
        "chapter_hook": "NULL-001在入职培训中对破冰游戏规则产生奇怪冲动——想找出漏洞",
        "emotion_ratio": "3:3:4",
        "skill_unlocked": "",
    },
    {
        "chapter": 48,
        "arc": "第三阶段：终极解密",
        "core_event": "NULL-001在地铁上看着城市，备忘录里出现不是自己想写的话。最终画面",
        "face_slap_target": "系统/永恒轮回",
        "face_slap_method": "传承——有人在借他的手写下给下一个NULL-002的留言",
        "husband_moment": "地铁驶入隧道，工牌发出微弱荧光，照片背景里有个模糊的女人正在回头",
        "chapter_hook": "最终句：欢迎入职。你的工牌，有点不对劲",
        "emotion_ratio": "3:3:4",
        "skill_unlocked": "",
    },
]

# ═══════════════════════════════════════
# 2. CHARACTERS: 人物初始状态
# ═══════════════════════════════════════
CHARACTERS = [
    {
        "name": "林默",
        "location": "永夜集团/入职培训室",
        "emotional_state": "冷静、疏离、死亡共情症初期",
        "known_secrets": "前大厂HR裁员优化师，裁过372人",
        "unknown_secrets": "已被系统标记为NULL-002预留宿主",
        "abilities_active": "规则裂隙审计（初级，代价：存在性折旧）",
        "abilities_locked": "HR模式（不稳定）、临终感知同步（未觉醒）",
        "dialog_fingerprint": "话少，反问句多，痛苦时用HR术语自我防御。愤怒时不提高音量，反而更冷静",
        "body_language": "紧张时摩挲工牌边缘，痛苦时掐掌心至出血，切换HR模式后坐姿挺直如面试",
        "physical_description": "眼尾有疲惫的细纹，右手小指后期失去触觉，面部逐渐模糊化（NULL化）",
    },
    {
        "name": "苏晚",
        "location": "永夜集团/消防通道",
        "emotional_state": "创伤后麻木、规则依赖、外冷内热",
        "known_secrets": "司龄7年（实际入职3个月），被系统重置过七次",
        "unknown_secrets": "她是第三轮复用账号，第一轮为救初代NULL而死",
        "abilities_active": "规则执行力极强，熟悉公司生存法则，随身携带清醒剂",
        "abilities_locked": "上一轮HR残留权限（第24章解锁）、认知锁突破能力",
        "dialog_fingerprint": "语气冷淡命令式，极少解释，警告时直接用'你会死'。情绪波动时咬下唇",
        "body_language": "站姿永远靠墙或靠门（保持逃生路线），手指无意识敲大腿（像在计时），后期眼角出现皱纹白发",
        "physical_description": "二十出头的脸，但眼神像四十岁。后期头发出现白发，眼角有皱纹",
    },
    {
        "name": "张经理",
        "location": "永夜集团/顶楼核心机房",
        "emotional_state": "疲惫、三百年孤独、寻求解脱",
        "known_secrets": "初代NULL-000，曾是上一轮试图拯救所有人的HR，最后选择成为守门人",
        "unknown_secrets": "他其实一直在寻找敢'拒绝接替'的人，分散协议是谎言",
        "abilities_active": "NULL-000权限，可修改公司规则，掌控所有认知隔离带",
        "abilities_locked": "无（已全部解锁，但正在燃烧殆尽）",
        "dialog_fingerprint": "陈述句为主，像在读年报。赞许时不笑，只点头。最后阶段只剩一张嘴能说话",
        "body_language": "身体大部分留白化，只剩嘴和耳朵。站立时像一具被掏空的西装",
        "physical_description": "照片完全空白，工牌编号NULL-000。消散前展示退休工牌：普通地铁卡，名字张伟",
    },
    {
        "name": "陈雨",
        "location": "永夜集团/B3层玻璃舱NULL-001",
        "emotional_state": "意识碎片状态，只剩核心记忆",
        "known_secrets": "第1章被林默救下的实习生，认知被部分格式化",
        "unknown_secrets": "她将成为系统病毒，随每次系统复制而传播",
        "abilities_active": "无（被格式化状态）",
        "abilities_locked": "系统病毒（第34章解锁）——每个新系统都携带她的意识水印",
        "dialog_fingerprint": "初期机械重复'谢谢'，后期只说一句话：我会成为每一个新系统的噩梦",
        "body_language": "B3层时机械敲击虚空键盘，成为病毒后在系统中无处不在",
        "physical_description": "工牌照片边缘模糊，舱体标签NULL-001。后期无实体，仅存于系统噪音中",
    },
    {
        "name": "老周",
        "location": "永夜集团/废弃会议室",
        "emotional_state": "绝望、寻求解脱、对留白者的病态向往",
        "known_secrets": "破规者组织首领，想主动格式化成为完美留白者",
        "unknown_secrets": "他解脱的微笑暗示他成为了系统噪音的一部分",
        "abilities_active": "掌握公司内部调令信息，知晓顶楼核心机房存在",
        "abilities_locked": "无",
        "dialog_fingerprint": "说话像临终遗言，每句带'算了'。邀请人时用'来吧， blank is bliss'",
        "body_language": "佝偻，总是抱着自己的工牌像抱婴儿，被拖走时微笑",
        "physical_description": "四十多岁，头发花白，工牌照片清晰但眼神死寂",
    },
]

# ═══════════════════════════════════════
# 3. DEBTS: 债务（情感/秘密的埋收时间表）
# ═══════════════════════════════════════
DEBTS = [
    {
        "debt_id": "debt_001",
        "type": "存在性折旧",
        "content": "林默每次使用规则裂隙，工牌照片模糊、亲人遗忘、自我溶解。从12%到100%",
        "bury_chapter": 1,
        "collect_chapter": 41,
        "status": "active",
    },
    {
        "debt_id": "debt_002",
        "type": "心理创伤",
        "content": "林默裁过372人，死亡共情症源于此。必须在最终章与自我和解",
        "bury_chapter": 7,
        "collect_chapter": 36,
        "status": "active",
    },
    {
        "debt_id": "debt_003",
        "type": "身世之谜",
        "content": "苏晚被系统重置过七次，她是第三轮复用账号，第一轮为救初代NULL而死",
        "bury_chapter": 9,
        "collect_chapter": 26,
        "status": "active",
    },
    {
        "debt_id": "debt_004",
        "type": "亲情代价",
        "content": "母亲被系统录入为纯净容器抽取情感能量，林默的自救以母亲痛苦为燃料",
        "bury_chapter": 23,
        "collect_chapter": 24,
        "status": "active",
    },
    {
        "debt_id": "debt_005",
        "type": "真相揭露",
        "content": "分散协议是骗局，真正协议是替换——新NULL顶替旧NULL。守门人是耗材",
        "bury_chapter": 25,
        "collect_chapter": 40,
        "status": "active",
    },
    {
        "debt_id": "debt_006",
        "type": "拯救承诺",
        "content": "陈雨被林默救下但认知格式化，林默承诺要救她出来",
        "bury_chapter": 1,
        "collect_chapter": 34,
        "status": "active",
    },
    {
        "debt_id": "debt_007",
        "type": "爱情创伤",
        "content": "苏晚第一轮爱上初代NULL（张经理），他选择成为守门人删除了关于她的记忆",
        "bury_chapter": 25,
        "collect_chapter": 26,
        "status": "active",
    },
]

# ═══════════════════════════════════════
# 4. FORESHADOWING: 伏笔总表
# ═══════════════════════════════════════
FORESHADOWING = [
    {
        "fs_id": "fs_001",
        "bury_chapter": 1,
        "content": "工牌照片从彩色褪为黑白，存在性折旧12%",
        "collect_chapter": 48,
        "type": "物品伏笔",
        "status": "active",
    },
    {
        "fs_id": "fs_002",
        "bury_chapter": 3,
        "content": "记忆锚点笔记本空白页背面出现不是自己的字迹：别相信司龄",
        "collect_chapter": 44,
        "type": "物品伏笔",
        "status": "active",
    },
    {
        "fs_id": "fs_003",
        "bury_chapter": 1,
        "content": "母亲问林默：你是谁？我们认识吗？",
        "collect_chapter": 47,
        "type": "情感伏笔",
        "status": "active",
    },
    {
        "fs_id": "fs_004",
        "bury_chapter": 3,
        "content": "笔记本上的字：别相信司龄",
        "collect_chapter": 47,
        "type": "信息伏笔",
        "status": "active",
    },
    {
        "fs_id": "fs_005",
        "bury_chapter": 1,
        "content": "实习生陈雨认知被格式化，变成留白者雏形",
        "collect_chapter": 34,
        "type": "人物伏笔",
        "status": "active",
    },
    {
        "fs_id": "fs_006",
        "bury_chapter": 18,
        "content": "张经理工牌照片完全空白，编号NULL-000",
        "collect_chapter": 36,
        "type": "身份伏笔",
        "status": "active",
    },
    {
        "fs_id": "fs_007",
        "bury_chapter": 16,
        "content": "市场部深处一扇门，锁是林默的工牌编号",
        "collect_chapter": 28,
        "type": "场景伏笔",
        "status": "active",
    },
    {
        "fs_id": "fs_008",
        "bury_chapter": 17,
        "content": "墙壁最底部有未刻上的凹槽，尺寸正好是林默的工牌",
        "collect_chapter": 32,
        "type": "场景伏笔",
        "status": "active",
    },
    {
        "fs_id": "fs_009",
        "bury_chapter": 8,
        "content": "老周被拖走时露出解脱的微笑",
        "collect_chapter": 19,
        "type": "人物伏笔",
        "status": "active",
    },
    {
        "fs_id": "fs_010",
        "bury_chapter": 13,
        "content": "王磊的残影工牌，编号指向B3层服务器机柜",
        "collect_chapter": 14,
        "type": "物品伏笔",
        "status": "active",
    },
    {
        "fs_id": "fs_011",
        "bury_chapter": 14,
        "content": "陈雨玻璃舱编号NULL-001",
        "collect_chapter": 34,
        "type": "身份伏笔",
        "status": "active",
    },
    {
        "fs_id": "fs_012",
        "bury_chapter": 1,
        "content": "地铁陌生人（大纲设定中的镜像伏笔）",
        "collect_chapter": 45,
        "type": "人物伏笔",
        "status": "active",
    },
    {
        "fs_id": "fs_013",
        "bury_chapter": 32,
        "content": "系统为苏晚准备了NULL-003预留位",
        "collect_chapter": 44,
        "type": "身份伏笔",
        "status": "active",
    },
]

# ═══════════════════════════════════════
# 5. RULES: 写作硬规则
# ═══════════════════════════════════════
RULES = [
    {
        "rule_type": "设定",
        "rule_content": "永夜集团是异空间机构，与现实次元壁绝对隔离。不涉及现实劳资纠纷",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "设定",
        "rule_content": "规则描述必须用冷峻客观的条款体（如'第X条：违者将...'），与情感描写形成强烈反差",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "人设",
        "rule_content": "林默使用能力后必须用极端物理刺激保持清醒（冰水浇头/强光照射/窒息感），不能自然恢复",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "人设",
        "rule_content": "苏晚说话冷淡命令式，极少解释。情绪波动时咬下唇，不是哭",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "人设",
        "rule_content": "张经理说话像读年报，陈述句为主。赞许时不笑只点头",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "节奏",
        "rule_content": "每章至少一次规则裂隙审计或HR模式的使用，或一次打脸/高光时刻",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "节奏",
        "rule_content": "每5章必须更新一次NULL化进度（12→23→41→53→67→78→89→94→100），作为视觉进度条",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "节奏",
        "rule_content": "每章末尾必须有章末钩子，最后100字内完成，让读者心痒",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "节奏",
        "rule_content": "结尾结构必须轮换，禁止连续两章使用'静止动作+物品特写'式收束。推荐：对话戛然而止、环境突变、反直觉动作、第三方介入、视角抽离",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "文风",
        "rule_content": "恐怖/痛苦场景感官比喻不得超过3个，第4个必须是留白、沉默、或主角意识中断。过度描写杀死恐怖感",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "文风",
        "rule_content": "禁止在800字范围内重复使用同一种修辞结构（如'不是X是Y'、'像……一样'的排比）。真人作者会刻意换花样，AI必须模仿这种'审美羞耻'",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "文风",
        "rule_content": "紧张/恐惧状态下的感知必须模糊化。'好像'、'似乎'、'不确定是不是'比精确测量更有力量。人类在极端情绪下是失焦的",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "人设",
        "rule_content": "林默每章必须至少有一个'废动作'——与主线无关、暴露他是活人的细节（走神、肚子叫、注意到主管的鼻毛、想起早餐味道）。这是'人味'的来源，是AI最难生成的东西",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "设定",
        "rule_content": "规则漏洞不得被'轻松破解'。破解必须伴随犹豫、恐惧、身体代价、系统的反扑。完美逻辑闭环是程序员的自我满足，不是文学",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "禁用",
        "rule_content": "禁止出现血腥自残描写。统一用冰水/强光/窒息感等极端物理刺激替代",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "禁用",
        "rule_content": "禁止出现'然而'、'不得不说'、'众所周知'、'突然'、'竟然'、'原来'、'与此同时'",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "文风",
        "rule_content": "描写多用五感（触觉优先级最高：冰冷、麻木、刺痛），少用心理旁白，用身体反应代替情绪描述",
        "enforcement_level": "soft",
    },
    {
        "rule_type": "文风",
        "rule_content": "环境描写必须做减法：删掉50%无叙事功能的环境细节，只保留一个核心锚点，并赋予它叙事功能（如'椅子间距一米五'→暗示曾被绑缚）",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "文风",
        "rule_content": "比喻必须私有化：禁止用公共库存比喻（如'细线吊着嘴角''溺水者看浮木''磁带被水浸过'）。林默的比喻必须带着HR视角的绩效评估冷酷感，苏晚的比喻必须带着规则执行者的精确感",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "文风",
        "rule_content": "金手指的呈现必须是认知错位，不是游戏UI。禁止'黑色背景绿色字'的赛博朋克式代码流，改用肉体层面的不适（融化、粘连、高温、失焦）",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "文风",
        "rule_content": "禁止在相邻两段使用'不是X，是Y'或'不是……是那种……'句式。用具体感受替代：'肌肉记忆'替代'那种听到关键词的条件反射'，'定格在最后一帧'替代'像被细线吊着'",
        "enforcement_level": "hard",
    },
    {
        "rule_type": "文风",
        "rule_content": "对话推动情节，规则条款与情感对话交替出现，形成压迫-释放节奏",
        "enforcement_level": "soft",
    },
]

# ═══════════════════════════════════════
# 6. SKILLS: 技能树
# ═══════════════════════════════════════
SKILLS = [
    {
        "skill_name": "规则裂隙审计",
        "unlock_chapter": 1,
        "description": "看见规则底层漏洞，找到表述矛盾或定义盲区。代价：存在性折旧",
        "used_chapters": "",
    },
    {
        "skill_name": "临终感知同步",
        "unlock_chapter": 2,
        "description": "100%体验他人死前的绝望与痛苦。可触发共情症熔断",
        "used_chapters": "",
    },
    {
        "skill_name": "HR模式",
        "unlock_chapter": 7,
        "description": "情感剥离，绝对理性计算。事后加倍反噬（呕吐、撞墙、失禁）",
        "used_chapters": "",
    },
    {
        "skill_name": "记忆碎片植入",
        "unlock_chapter": 20,
        "description": "在轮回重置中向不同员工植入记忆碎片，改写集体潜意识",
        "used_chapters": "",
    },
    {
        "skill_name": "NULL序列权限",
        "unlock_chapter": 21,
        "description": "被系统标记为NULL-002/003，可触发协议冲突、制造系统死锁",
        "used_chapters": "",
    },
    {
        "skill_name": "意识绑定/系统病毒化",
        "unlock_chapter": 34,
        "description": "将意识与系统底层协议绑定，成为无法消化的水印/病毒",
        "used_chapters": "",
    },
]
